# Generated by Django 4.0.4 on 2022-04-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
                ('date_updated', models.DateTimeField(verbose_name='date_updated')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by', models.CharField(max_length=200)),
                ('comment_desc', models.CharField(max_length=2000)),
                ('commented_at', models.DateTimeField(verbose_name='created_at')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs')),
            ],
        ),
    ]
