# Generated by Django 4.0.4 on 2022-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['title'], 'verbose_name': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='date_updated'),
        ),
    ]
