# Generated by Django 4.0.4 on 2022-04-28 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date_updated',
            field=models.DateTimeField(blank=True, verbose_name='date_updated'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_blog', to='blogs.blogs'),
        ),
    ]
