# Generated by Django 4.0.4 on 2022-05-14 01:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 5, 14, 1, 17, 37, 812647, tzinfo=utc), verbose_name='date_created')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='date_updated')),
                ('date_published', models.DateTimeField(blank=True, null=True, verbose_name='date_published')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by', models.CharField(max_length=200)),
                ('comment_desc', models.TextField()),
                ('commented_at', models.DateTimeField(default=datetime.datetime(2022, 5, 14, 1, 17, 37, 871489, tzinfo=utc), verbose_name='created_at')),
                ('is_approved', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog')),
            ],
            options={
                'ordering': ['commented_at'],
            },
        ),
        migrations.RemoveField(
            model_name='comments',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
